package com.example.c_p.beans;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * @param id          Autogenerated by spring as an int type
 * @param Category    An enum which defines which type of Coupon is being
 *                    produced
 * @param title       A name for produced coupon, String type
 * @param description A description for the produced coupon, String type
 * @param startDate   a Date type of which the coupon starts being valid at
 * @param endDate     a Date type of which the coupon finishes being valid at
 * @param amount      an int type to represent the amount of Coupons produced
 * @param price       describes the price of a coupon in the Double type
 * @param image       a String type which can be linked as an Image URL to
 *                    display the coupon visually
 * @param customers   an ArrayList of customers ; which link between the coupons
 *                    who were purchased by other people
 */

@Entity
@Table(name = "coupons")
public class Coupon {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	@ManyToOne(fetch = FetchType.LAZY)
	private Company company;
	@Column(name = "categoryId")
	@Enumerated(EnumType.ORDINAL)
	private Category category;
	private String title;
	private String description;
	private Date startDate;
	private Date endDate;
	private int amount;
	private double price;
	private String image;

	@ManyToMany(fetch=FetchType.EAGER)
	@JoinTable(name = "customers_coupons", joinColumns = @JoinColumn(name = "coupon_id"), inverseJoinColumns = @JoinColumn(name = "customer_id"))
	List<Customer> customers = new ArrayList<Customer>();
	
	
	
	public Coupon() {
		super();
	}

	public Coupon(int id, Company company, String title, String description,Category category, Date startDate, Date endDate, int amount,
			double price, String image) {
		super();
		this.id = id;
		this.category = category;
		this.company = company;
		this.title = title;
		this.description = description;
		this.startDate = startDate;
		this.endDate = endDate;
		this.amount = amount;
		this.price = price;
		this.image = image;
		
	}

	public Coupon(Company company, String title, String description,Category category, Date startDate, Date endDate, int amount,
			double price, String image) {
		super();
		this.company = company;
		this.title = title;
		this.category = category;
		this.description = description;
		this.startDate = startDate;
		this.endDate = endDate;
		this.amount = amount;
		this.price = price;
		this.image = image;
	}

	public Company getCompany() {
		return company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Category getCategory() {
		return category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public int getAmount() {
		return amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public List<Customer> getCustomers() {
		return customers;
	}

	public void setCustomers(List<Customer> customers) {
		this.customers = customers;
	}

	@Override
	public String toString() {
		return "Coupon [id=" + id +  ", category=" + category + ", title=" + title
				+ ", description=" + description + ", startDate=" + startDate + ", endDate=" + endDate + ", amount="
				+ amount + ", price=" + price + ", image=" + image +  "]";
	}

}
